# Generated by Django 4.2.1 on 2023-05-25 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
