# Generated by Django 4.2.1 on 2023-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tinymce_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinymce',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
