# Generated by Django 4.2.1 on 2023-06-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tinymce_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinymce',
            name='pub_url_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tinymce',
            name='published_url',
            field=models.URLField(default=''),
        ),
    ]
